### ISSUE TITLE
[FAILING TEST] Unit testing a NestJS Service that consumes a TypeORM Repository

### ISSUE THREAD

**Issue by jrista** [jmcdo29/testing-nestjs#1298] opened 2021-03-28 19:39 UTC
**Describe the bug**

I am trying to unit test some services we have in a project that uses TypeORM. We wrap the repositories in services so we can abstract the repo away from the rest of the code and just rely on the services (which are easy to mock). 

We couldn't quite get any of our own mocks to work at first, then eventually came across the @golevelup/nestjs-testing module. We've fiddled with that for a bit, found your examples and applied that pattern, but still seem to be having problems. All of our tests that use getRepositoryToken and createMock time out. 

**To Reproduce**

Model:
```ts
import { Column, Entity, Index, ObjectIdColumn } from 'typeorm';

export class NgbDate {
  @Column() year: number;
  @Column() month: number;
  @Column() day: number;
};

export class DemoBenefit {
  @Column() categoryId: number;
  @Column() subCategoryId: number;
  @Column() quantity: number;
}

@Entity('demoaccounts')
@Index(['cardNumber'], { unique: true })
export class DemoAccount {
  @ObjectIdColumn() _id?: string;
  @Column() authorityId: number;
  @Column() cardNumber: string;
  @Column() householdId?: string;
  @Column() binCode: string;
  @Column() name: string;
  @Column() startDate: NgbDate;
  @Column() endDate: NgbDate;
  @Column() isCardActivated?: boolean;
  @Column(type => DemoBenefit) benefits: DemoBenefit[];
}
```

Service:
```ts
import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { DemoAccount } from './demo-account.model';

@Injectable()
export class DemoAccountService {
  constructor(@InjectRepository(DemoAccount, 'mongo') private readonly repository: Repository<DemoAccount>) {
  }

  async findByCardNumber(cardNumber: string): Promise<DemoAccount | undefined> {
    return this.repository.findOne({ cardNumber });
  }
}
```

Tests:
```ts
import { createMock } from '@golevelup/nestjs-testing';
import { DeepMocked } from '@golevelup/nestjs-testing/lib/mocks';
import { INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { DemoAccount } from './demo-account.model';
import { DemoAccountService } from './demo-account.service';

describe('DemoAccountService', () => {
  let module: TestingModule;
  let service: DemoAccountService;
  let repo: DeepMocked<Repository<DemoAccount>>;
  let app: INestApplication;

  beforeEach(async () => {
    jest.setTimeout(30000);
    module = await Test.createTestingModule({
      providers: [
        DemoAccountService,
        {
          provide: getRepositoryToken(DemoAccount, 'mongo'),
          useValue: createMock<Repository<DemoAccount>>(),
        },
      ],
    }).compile();

    service = module.get(DemoAccountService);
    repo = module.get(getRepositoryToken(DemoAccount, 'mongo'));
    app = module.createNestApplication();
    await app.init();
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('findByCardNumber()', () => {
    it('should return entity when found by card number', async () => {
      const demoAccount: DemoAccount = {
        authorityId: 15,
        cardNumber: '1234569999999999',
        name: 'TEST DEMO CARD',
        binCode: '123456',
        startDate: {  year: 2020, month: 3, day: 1 },
        endDate: { year: 2020, month: 3, day: 31 },
        benefits: [
          { categoryId: 1, subCategoryId: 0, quantity: 2 },
          { categoryId: 2, subCategoryId: 0, quantity: 4 },
        ]
      };

      repo.findOne.mockResolvedValue(demoAccount);

      expect(await service.findByCardNumber('1234569999999999')).toEqual(demoAccount);
    });
  });
});
```

Simple NestJS project with this service/entity and test should be sufficient to replicate the problem. 

**Expected behavior**
Unit tests that run in a timely manner without timing out. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 7.5.6

**Additional context**

```
Error: Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.
Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 30000 ms timeout specified by jest.setTimeout.
    at mapper (/Users/jonrista/contracts/wicshopper-benefits-server/node_modules/jest-jasmine2/build/queueRunner.js:27:45)
    at /Users/jonrista/contracts/wicshopper-benefits-server/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jmcdo29** [comment] 2021-03-28 19:42
What's the reason for `module.createNestApplication` in this unit test?

**Comment by jrista** [comment] 2021-03-29 05:11
It was paving the way for future tests, which ended up getting broken out into an integration spec file. 

I think the @golevelup/nestjs-testing module is just broken. It is at v0.1.2, and I just couldn't get it working. I finally resorted to creating very basic jest.fn() based mocks, which I then mockedResolvedValues for on a test-by-test case basis, and that seemed to work.

**Comment by jmcdo29** [comment] 2021-03-29 05:13
Gotcha. What if you use `@golevelup/ts-jest` (same package but new name and updates). If it still has problems could you provide a reproduction so I can take a deeper look?

**Comment by jrista** [comment] 2021-03-30 18:14
Sure, I'll give it a whirl today.

**Comment by jrista** [comment] 2021-04-15 07:34
So, in the long run, we decided we didn't necessarily need the @golevelup stuff. At least, not the testing stuff (we use other packages from them). The testing stuff just doesn't seem to be ready, and isn't even listed in their repos, so we decided to just mock things manually (which turned out to be easier than it seemed at first.)

**Comment by jmcdo29** [comment] 2021-04-16 17:54
The testing package is under the [`nestjs`](https://github.com/golevelup/nestjs) repository. Either way, glad you got something that worked for you. Closing the issue out.

**Closed by jmcdo29** 2021-04-16 17:54 UTC
Labels: bug
